name: Label PRs when approved

on: 
  pull_request_review:
    types: [submitted]

jobs:
  label-when-approved:
    runs-on: ubuntu-latest

    steps:
      - name: Label PR when approved
        uses: pullreminders/label-when-approved-action@main
        env:
          APPROVALS: '1' # Number of required approvals
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "Approved" # Label to add when PR is approved


